### ISSUE TITLE
[Mobile] Edit Profile | Cannot edit Facebook / LinkedIn / Twitter / Github fields

### ISSUE THREAD

**Issue by hellynyc** [FightPandemics/FightPandemics#1022]
Device/OS/Browser: OnePlus 7 Pro / OS10 / Chrome

Expected Result: User should be able to change their Facebook / LinkedIn / Twitter / Github URLs.
Actual Result: Facebook / LinkedIn / Twitter / Github URLs fields have default text that cannot be edited.

**Comment by idjevm** [comment]
I think you are supposed to add only your username for each platform instead of a whole link - so the default text is the URL and the only thing missing should be your username. Not an issue so closing this one. Also please refer to this document in [how to create an issue for our GitHub Repo](https://github.com/FightPandemics/FightPandemics/wiki/How-to-%22Properly%22-create-a-ticket---new-issue)

**Comment by hellynyc** [comment]
I see. Gotcha. It's not very intuitive. Maybe there can be grayed out text that says enter your username or something?

And sorry about the inconsistency, I also didn't have full access to Github, I will follow the guidelines for creating issues moving forward. Thanks for the help!

**Comment by idjevm** [comment]
Please request GitHub access to @manualzuru in Slack. And yeah, I mean that is for enhancement but bring it up on the engineering frontend channel :)

**Comment by hellynyc** [comment]
Yea, I have access now. Thanks, JV!

OK, I will bring up the idea with frontend engineering. Thanks.
