### ISSUE TITLE
Iphone XR not displaying dropdown list with location data

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#1165]
Issue : On my Iphone XR , as I enter location data (for Ex: zipcode), drop down list with related data not showing up.
steps:(on safari)
1.Go to Staging. https://staging.fightpandemics.work/
2.navigate to 'View Help Board'
3.Go to location
3.Enter zipcode
4.No drop-down list dispalyed  as shown in video below
https://share.getcloudapp.com/p9uPyZW7

expected: drop-down list with related data should appear as the user provides location info

**Comment by sheeba1** [comment]
@vikjoshi ,please feel free to change  release label , if needed

**Comment by sheeba1** [comment]
@rabbi08  tested .fine on iphone 11 https://fightpandemics.slack.com/files/U015XBKFRHA/F01795GFRTN/rpreplay_final1594751316.mp4

@nivetheatha tested and fine on samsung galaxy

**Comment by joshmorel** [comment]
His @sheeba1 Something similar was reported earlier https://github.com/FightPandemics/FightPandemics/issues/1119#issue-655037639 but they never responded to my question.

I had a feeling it is something related to a feature that antd is using that the browser doesn't support.  BUT now I have been trying BrowserStack I see with onboarding it works, but for filters it doesn't so that may be a clue. It would be nice to have more than 1 minute to debug (we need that partnership!).

To confirm. Which browser are you using, Safari or Chrome?

**Comment by vikjoshi** [comment]
@joshmorel on both safari and chrome

**Comment by joshmorel** [comment]
Interesting. I am pretty sure it has something to do with z-index https://stackoverflow.com/a/58490946/4582054

Both the modal (from `antd-mobile`) and the select (from `antd`) utilize z-index and the modal has `translateZ(1px)` and might be related. Another time where using `antd-mobile` and `antd` together is causing some weird issues...

**Comment by dabartlett** [comment]
I think this is the same issue I entered on 1119 defect.

**Comment by vikjoshi** [comment]
@joshmorel , I am assigning this to you for right now because it is related to geolocation but can reassign if needed. Thanks!

**Comment by joshmorel** [comment]
@vikjoshi that's okay for now. I'm getting an idea of what might be the issue.

Having an iPhone device to emulate for more than 1 minute would be helpful. Until we partner with BrowserStack or other maybe we can use AWS Device Farm. I'll ask @mannykary .

**Comment by vikjoshi** [comment]
@joshmorel i have access to an XR- let me know if I can help

**Comment by joshmorel** [comment]
Thanks @vikjoshi I will ask you & @sheeba1 to confirm when I think I've got it.

If the situation is complicated (I'll need to override some the styles from one or both of 2 external dependencies) an emulator would be helpful but I can make do for now (+ hopefully it's not too complicated - maybe only a single CSS rule?).

**Comment by joshmorel** [comment]
@vikjoshi @sheeba1 @dabartlett Can you test on https://featurefix-iphone-overlay-bug.fightpandemics.xyz

I tried once on Safari on BrowserStack and it worked. I couldn't test Chrome because I ran out of time on time and valid devices*. 


*It seems BrowserStack doesn't upgrade emulated devices to newer OS version.

This isn't supported (used on feed for infinite scroll) up to iOS 12.01 and I think with BrowserStack you test at where the OS was at the time of release (maybe?) 
https://caniuse.com/#feat=intersectionobserver
![image](https://user-images.githubusercontent.com/10546720/87581402-df36c200-c6a6-11ea-99f6-bd6bab4faad2.png)

It seems [iPhone 6S](https://www.digitaltrends.com/mobile/how-to-download-ios-13/) are upgraded to iOS 13 so we should be fine, no? If you think we need to support older devices we'd need to open another issue but it would be a lot of work to address this.

**Comment by vikjoshi** [comment]
@joshmorel tested on both safari and chrome on iPhone XR and it is working as expected! 

Yeah, for now lets not worry about pre iPhone 6s

**Comment by sheeba1** [comment]
tested and worked fine on iphone XR ,safari
![image](https://user-images.githubusercontent.com/65972693/87596599-418ec300-c6a5-11ea-8b8d-6844810c691f.png)

**Comment by sheeba1** [comment]
@rabbi08 @nivetheatha can you please test on your devices ,just to make sure its working fine and did not breaking already working code.Thanks!

**Comment by nivetheatha** [comment]
@sheeba1 works fine in Android devices.

**Comment by rabbi08** [comment]
I have re-tested on iPhone-11 and it is working as expected. Thanks

**Comment by dabartlett** [comment]
Tested with iphone 6S after upgrading to version 13 and it works as well. thank you

![image](https://user-images.githubusercontent.com/67716598/87695719-b238ec80-c744-11ea-95c9-ea717d722ff2.png)
