### ISSUE TITLE
Google Maps Display for Local Health Facilities

### ISSUE THREAD

**Issue by pthoma14** [FightPandemics/FightPandemics#1201]
“As an individual,
I want to visually see the nearest health facilities to my current location
so that I can see how far I might have to travel to get to them”

**Acceptance Criteria:**
* Display 10-mile (16km) radius 
* Display Nearest Health Facilities within that radius

**Feature Requirements:** 
https://www.notion.so/fightpandemics/a729bd46f001461393a0ad707161f299?v=16cb1b0a7a1c4d5ba0a1aea6184cf734&p=1769f08b2b7e4044a7c67fd363bdcb51

**Design:**
![Screen Shot 2020-07-17 at 8 18 47 AM](https://user-images.githubusercontent.com/6046237/87802475-25566780-c806-11ea-8bd5-23b2f04843b8.png)

![image](https://user-images.githubusercontent.com/6046237/87802177-a4976b80-c805-11ea-9560-cd9efa30fb60.png)

**Comment by inblack67** [comment]
@pthoma14 Has the functionality of converting the address submitted from the client to the GeoJSON field which will contain the lat long been handled on the Node.JS backend or not?

**Comment by pthoma14** [comment]
> @pthoma14 Has the functionality of converting the address submitted from the client to the GeoJSON field which will contain the lat long been handled on the Node.JS backend or not? 


@inblack67 No, I don't believe it has. 

I was working with @Chimaobi-Johnson back in May and the last thing we discussed is that the google map api key was not integrated yet.

**Comment by joshmorel** [comment]
I'll outline the current state of geolocation in the app here for whomever works on this.

We are using the backend to query the [Google Maps API (aka gmaps)](https://cloud.google.com/maps-platform/pricing). The rationale is to have one place to control the logic of converting an address or coordinates into our standardized location model for multiple clients. Additionally, it's we can easily protect our API key if querying via the backend, however, we could still query from the client if necessary and restrict access by domain (fightpandemics.com) so no one can nefariously use our key.

We are using this to associate a location with a user profile or help board query.

The 3 current routes are:

1.  `api/geo/address-predictions` - returns address predictions quite similar to https://developers.google.com/maps/documentation/javascript/places-autocomplete. Currently we are only returning type=geocode as we don't want to return businesses etc when a user searches for an address.
2. `api/geo/location-details` - uses the placeId selected from 1 above to first fetch [place details from gmaps](https://developers.google.com/places/web-service/details) then transform it to our standard location model with coordinates, city, country, etc.
3. `api/geo/location-reverse-geocode`  - for use with getting coordinates from browser's [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API), to [reverse geocode from gmaps](https://developers.google.com/maps/documentation/geocoding/start#reverse) then transform it similar to 2 into our standard location model

Getting a list of nearest facilities could be done with a modified version of `api/geo/address-predictions` based on the user's location (if logged in, from that associated with their user's location, or by extending the existing LocationInput.js). However, an interactive map may require interacting with gmaps from the F/E directly. I will update with ideas soon.

**Comment by joshmorel** [comment]
@inblack67 why did you close this issue?

**Comment by joshmorel** [comment]
Anyways I'm re-opening because this is a unfinished work item to get f_healthfacilities done.

FYI @davidoduk this likely will include some backend work although I mentioned in slack its mostly frontend. I can work with whoever volunteers. I need to think a bit more about the map & using frontend vs backend for integrating with gmaps.

**Comment by joshmorel** [comment]
@davidoduk

Here is my proposal for the *Nearest Facility Map*:

I think we can meet the requirements, reduce complexity, keep handling of Google Maps integration on the backend & minimize usage of our Google Maps API credits if we use the [Map Static API](https://developers.google.com/maps/documentation/maps-static/overview)

* Instead of a dynamic/interactive map it returns an image (PNG by default, or JPG)
* This can include customized markers - like the 'H' in the above so it will meet the need
* I would propose we include a link to open in a new tab to Google Maps itself if they do indeed want to see in interactive map (get directions by car or walk etc)

The user could input address or autocompletion or get coordinates (as per existing LocationInput.js) / or for logged in use existing Location, send to backend then get a an ordered list of nearest facilities & the map.

I think we'd get the facility list via - https://developers.google.com/places/web-service/search 

A few product questions:

1. Health Facilities - what is included, just hospitals like example, also doctor offices? The latter might make more sense (not just hospitals).
2. "Display 10-mile (16km) radius". This may be too small for rural areas... For example I am semi-rural and only have one hospital within that radius (3-4 doctor's offices). Someone more rural may only have 1-2 doctor's offices in such a radius or none. Maybe a number is better - like nearest 10 and size map to these locations?

**Comment by joshmorel** [comment]
As a final point if it makes more sense to request especially the static map (but even the facilities list) directly from the frontend, that's fine. We can add a 2nd key and protect it via HTTP referrer restriction:

![image](https://user-images.githubusercontent.com/10546720/91333059-1070da80-e79b-11ea-889e-df2b22a08433.png)

**Comment by davidoduk** [comment]
@joshmorel , Is it possible to have a link on every highlighted H on the returned static image? If so, let's do it. Answers to the questions
1. Makes sense to display all health care facilities/doctors offices
2. Agreed with this, I think we should display the nearest 10 regardless of how close or far they are. A future upgrade can have the user select their search distance

**Comment by joshmorel** [comment]
> to have a link on every highlighted H on the returned static image? If so, let's do it. Answers to the questions

Hey @davidoduk  - no for that you'd need either:

1) [Maps JavaScript API](https://developers.google.com/maps/documentation/javascript)
2) [Maps Embed API](https://developers.google.com/maps/documentation/embed/get-started)

The latter might be the simpler option of the two. Anyways, I've never actually done anything with the Maps API just geocoding/autocomplete. 

So whoever takes the lead needs to explore the different APIs and see what will meet the need. There is already some frontend code - they can use that if it will work. Although probably the best would be to use our existing LocationInput.js & backend routes - and then get the map/nearest facilities via a call from the frontend. However, I'd only be able to figure out the best choice by getting started and trying different things - so that's what the assigned person should do.

**Comment by maskowe** [comment]
Josh and David,   To start -- is it a final decision to go with the Map Static API?   Let me have an answer to this before I start, because it would probably be easier for me to start with the google-maps-react npm package.   Thanks!

**Comment by davidoduk** [comment]
@maskowe , yes let's go with the Map Static API. I'll go with Josh's suggestion

**Comment by maskowe** [comment]
OK -  It might be limited to 25 markers (I know that initial requirements are for 10).   Will verify that later.

**Comment by davidoduk** [comment]
We shouldn't need up to 25, I think 10 is plenty enough
