### ISSUE TITLE
Customize "Share My Location" geolocation error message

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1254]
Instead of generic message on failure - https://github.com/FightPandemics/FightPandemics/blob/35b8a913070f92ede237d00a9083c500d0012703/client/src/utils/geolocation.js#L10 - customize the error message based on error code: https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPositionError

Most importantly for the case where it was previously denied - so it is clear to the user and they can rectify. See also #1253

**Comment by Serhazor** [comment]
Changed and submitted PR, getting an error, not sure what it means :-)

**Comment by RF9A5V** [comment]
Hey @joshmorel,

I've got a PR for this at #1348. Still a WIP, since I'm not sure what the best message to provide to the users would be for each of the cases. Right now it's set up to show the default error message associated with each error code, but that might be jarring for a non-technical user. Additionally, I've got the permissions error set up to provide a link to a support page to reset location permissions, but it's hardcoded to Chrome right now. Would doing browser detection and showing the relevant support page be necessary, or is that just overkill?

Thanks!

**Comment by joshmorel** [comment]
Hey @EyeWumbo . Yeah that would be overkill. I don't even think we should provide a link (most cases - this can be resolved with them needing to go elsewhere).

The 1st goal is to have something more informative than "failed getting location" so we don't run into this #1253 (in QA or real usage). Even a potentially "jarring" message is not so bad.

Beyond that it's really about what we want the user to do next depending on the type of errors - I see two general scenarios: 

1. If they [denied the permission](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPositionError) (maybe without even thinking), we can say "Failed getting location (error: _ACTUAL MESSAGE_). Please reset your browser's location permissions for this site or enter the address.". Either they've done this before or can search for docs - we don't need to give them a link.
2. For all other errors (including 5xx server error) we may just ask them "Failed getting location (error: _ACTUAL MESSAGE_). Please enter the address or try again.".

**Comment by RF9A5V** [comment]
Hey @joshmorel,

Updated according to guidance. Now we've just got the messages without anything special for links. Tested with rejecting permissions and throwing errors from the reverse location lookup endpoint.

Should now be ready for review.
