### ISSUE TITLE
Refactor and remove OrgProfileComplete page, instead use the ProfileCompleted page

### ISSUE THREAD

**Issue by jyclam** [FightPandemics/FightPandemics#1306]
The call to action button should say `View Help Board` unless the unlogged in user clicked on `Create a Post` and went through the sign up process, in which case it should say `Continue posting` 

# Currently the pages look like this:

## OrgProfileComplete
![screencapture-localhost-3000-create-organisation-complete-2020-07-30-17_47_07](https://user-images.githubusercontent.com/26049767/88989335-384e4a80-d290-11ea-9422-2f1b7d082383.png)

## ProfileCompleted
![screencapture-localhost-3000-profile-completed-2020-07-30-17_46_32](https://user-images.githubusercontent.com/26049767/88989339-3a180e00-d290-11ea-832d-a41cadd123ca.png)

**Comment by kterry1** [comment]
@jyclam I'll take this on, but I wanted to clarify the ask here. It says "Refactor and remove OrgProfileComplete page". Am I refactoring OrgProfileComplete, or completely deleting it and just using "ProfileCompleted" where "OrgProfileComplete" is used?

**Comment by kterry1** [comment]
Didn't mean to close. Let me know your thoughts on the above. I wanted to make sure I know what is wanted here before proceeding.

**Comment by kterry1** [comment]
Also, how can i differentiate whether the user went through "Create Post" and then signed up, or whether they signed up the usual way.?

**Comment by manualzuru** [comment]
Hi @kterry1, from my understanding, there are 2 different pages (UI wise) that are trying to accomplish the same function. The main difference is the 2nd CTA changes depending on the path that you went through. With the ProfileCompleted page, we should be able to do everything that is needed.

There are 3 paths with the last CTA that changes.

1- if you click in register -> Check the Help Board
2- if you try to make a comment + like and you aren't signed in. -> Check the Post (the post that you were liking or commenting)
3- if you click on Create Post and you aren't signed in. -> Continue Posting

Let me know if there are other questions🙏🏽

**Comment by kterry1** [comment]
Thanks @manualzuru! I'll dig into it today and see what I can do.

**Comment by kterry1** [comment]
@jyclam @manualzuru So I did some testing with this. Since the **Sign In**, **Create a post**, and **Join Now** buttons all take you to '/auth/signup', I'm not seeing a way to conditionally render the text based on the path the user took to get to '/profile-completed' or '/create-organisation-complete' and have it all happen in one page. If the wording of that button is really important, then I'd say we could stick with multiple pages, otherwise, here is what I had so far, but I don't think it really accomplishes what is asked for: https://share.getcloudapp.com/OAuqOwG0

Maybe @joshmorel or @idjevm have an idea?

_Side note: We need to change all instances of "organisation" in the codebase to "organization"._

**Comment by jyclam** [comment]
You can probably do a conditional `sessionStorage` like here https://github.com/FightPandemics/FightPandemics/blob/487e856300292dc7e754be23134b4025d3dfdb82/client/src/pages/PostPage.js#L161-L164
https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

**Comment by kterry1** [comment]
I'll give that a try. Thanks!

**Comment by kterry1** [comment]
The fix is based on jyclam's original post as it made the most sense.

**Comment by joshmorel** [comment]
@kterry1 @jyclam  Sorry I didn't take a look at this early when you tagged me - since the PR is in.

I'm really apprehensive about using the same file/component for different routes. It can result in a hard to maintain situation as I see with our "Login.js" file - see #1164  (that one is more complex, so not exactly comparable but similar principle). 

I think it would be better to have more re-usable components for similar pages but use one top-level file per route. You see this with a lot of filesystem based frameworks like vuex/next.js etc and I think it's a good approach.

With this PR #1328 - we need to fix the issues - but we should decide:

1. Make an exception here - and address the issues as described in my first comment in the PR
2. Or come up with a rule and stick to it - one file per route

Thoughts @robinv85 @idjevm ?

**Comment by joshmorel** [comment]
Also I did try to figure out what the design's flow is supposed to be after create org complete in Figma but it wasn't clear (https://www.figma.com/file/kT6SJLL4v3w06yFF2cGIun/FightPandemics-MVP?node-id=1852%3A8716). Is "View my profile" always supposed to go to MY profile as opposed to the recently created organisation's profile (current state). The latter makes more sense but the design doesn't indicate which. But also in such a case I'd expect the label to be different "View organisation" instead. 

Maybe the design was incomplete after copy/paste from user profile? Any insight into this @manualzuru
