### ISSUE TITLE
[Mobile UI bug] Profile elements are out of the screen

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1466]
### The Issue
On mobile, when opening Organisation or Individual Profile settings, elements already start outside of the screen:
![Screenshot_20200829-030432](https://user-images.githubusercontent.com/25089562/91630535-86965c80-e9a8-11ea-84f7-c428fce4706b.png)

When clicked on a field to complete, it gets worse:
![Screenshot_20200829-030454](https://user-images.githubusercontent.com/25089562/91630552-a0d03a80-e9a8-11ea-8a7f-7872818f2d21.png)

It also causes the draghandle for the drawer menu to move away from the right-hand side edge.

For Individual Profile it looks worse:
![Screenshot_20200829-050028](https://user-images.githubusercontent.com/25089562/91632062-a59aeb80-e9b4-11ea-84fb-3a4d649b94c3.png)

### How it should look
See [Zeplin screen](https://zpl.io/29W3yBd)  for reference

**Comment by CamilaArias** [comment]
I put it as P2 because it makes things straight up unreadable and it'd be expected that most of our users would be from mobile. But please change it if it's not appropriate.

**Comment by manualzuru** [comment]
@CamilaArias i also think that the disability icon might be better to have on the right side? Wdyt?

**Comment by emtay** [comment]
@CamilaArias should it be P1?

**Comment by cjohlmacher** [comment]
Hi, I looked into this as a first issue for me to get acquainted with the project.   My conclusion was that the Background component needed a width defined when screen size does not meet the tablet or desktop minimum width.   I also found that the input content overflowed off the page in some cases where the prefix is too long (LinkedIn and Facebook for example), so I changed the FormInput overflow to auto which seems to have fixed the problem. 
I will push those changes to Feature/1466 so that the folks with more experience with the project can review it.
