### ISSUE TITLE
'Apply filters' is overlapped by the footer if there is no post to display

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1622]
1. Navigate to helpboard and apply filter so that there is no result/post is returned.
Sample test data:
Provider: Startup
Type: Legal
-> apply filter

You will observe that no post exist.
Issue: When user scroll on this 'no post' page, you will observe that 'Apply filters' is overlapped with the footer of the page.

Refer attached GIF
https://share.getcloudapp.com/nOuneepw

Please note this works fine on mobile, refer below GIF
https://share.getcloudapp.com/nOunee82

**Comment by joshmorel** [comment]
![image](https://user-images.githubusercontent.com/10546720/95602094-6d121700-0a22-11eb-85eb-1fac653e3099.png)

~This issue also exists in prod but since I started looking into I'll just include this as well. Should be a quick fix.~

Actually I changed my mind. This is probably a good first issue for a frontend onboarding and not that urgent I don't think... Let's save it for someone else.
