### ISSUE TITLE
Visiblity of the Post from different account

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1629]
Environment-Staging
Device Used-Samsung S8
Browser-Google chrome
Steps to create:
1.Login with valid username and password.
2.Create a post as Individual-Request help (location :Bensaelem,Pa Visiblity:To state)
3.Log out.
4.Login with different account.
5.Choose offer help.
6.Choose "As a volunteer"
7.Provide location as "Bensalem,Pa"
Expected Result:
The post should be seen in the help board.
Actual result:
The post is not appeared in the help board.
Similarly for individual-offer help post ,org-req help post,org-offer help post also not visible when searched from different account .

**Comment by nivetheatha** [comment]
If the user is not logged in then we can able to see the post in the help board with the same steps.

**Comment by nivetheatha** [comment]
Environment:production 
The post is visible when we search through different account.

**Comment by rabbi08** [comment]
> Environment:production
> The post is visible when we search through different account.

@joshmorel 
This issue looks like regression issue.

**Comment by nivetheatha** [comment]
I think the profile address affects the search results in staging. If I have profile address as Bensalem, pa or any city from pa.I can able to see my post.If profile address is different state my post is not popping up.
But in production, irrespective of the profile address based on the search criteria the results are displayed.

**Comment by joshmorel** [comment]
Thanks @nivetheatha was able to recreate.

It is fetching the twice - once without location filter (thus overridden by logged in user), then again with location. 

This likely is a bug related `useEffect` or `useCallback` . @OzkanAbdullahoglu is this something you are able to look into any time soon? Otherwise I will or ask someone else but these can be tricky.

![fetch-twice-from-onboarding](https://user-images.githubusercontent.com/10546720/95665202-18eb5d80-0b1c-11eb-8f31-b7e7c7f29514.gif)

**Comment by OzkanAbdullahoglu** [comment]
@joshmorel Tomorrow I will be able to check this out.
