### ISSUE TITLE
Logged in user  and unlogged user gets different posts in the help board.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1631]
Environment -Staging 
Device used-Samsung s8
Browser-Google chrome 

Unlogged user
Offer help-->as a volunteer/as a donor-->only individual posts are shown
Offer help-->as a organization-->only organization posts are shown 
Logged in user
Offer help-->as a volunteer/donor-->both individual/organization posts are shown 
Offer help-->as a organization--> both individual/organization posts are shown

**Comment by nivetheatha** [comment]
Environment production 
Both unlogged user/login user got the same results 
Offer help-->as a volunteer/donor-->both individual/organization posts are shown
Offer help-->as a organization--> both individual/organization posts are shown

**Comment by joshmorel** [comment]
Thanks @nivetheatha . This code has been here for 3 months but never was actually running until now (due to changes in `useEffect` I think).

![image](https://user-images.githubusercontent.com/10546720/95665314-4553a980-0b1d-11eb-9acc-c641ac0d0a11.png)
https://github.com/FightPandemics/FightPandemics/blame/staging/client/src/pages/Feed.js

Basically if you selected "Organisation" it was supposed to show requesting help posts from individuals and vise versa. But it is actually doing the opposite when it runs (and not even showing them in the filter pane).

We need to fix also #1629 then maybe it will work like prod now? Or do we want to work as it was originally intended to work @manualzuru (don't think other PMs involved in feed for soft launch are still involved).
