### ISSUE TITLE
Post Filter: Integrate the location filter with the Google Maps API 

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#164]
The location filter filters Posts displayed in the Feed by location. Posts are filtered by the most specific location entered (e.g. if a state was selected, will filter by that state) and sorting by location (nearest posts first).

Requirements:
- User enters a location or clicks on "share my location", in the background we get the following information:
  - City, State, Country
- Save searched locations locally to prevent repeated API calls and to save Google Maps API credits.

<img width="955" alt="Screen Shot 2020-04-24 at 8 37 27 PM" src="https://user-images.githubusercontent.com/42228386/80270287-702f6b80-866b-11ea-92b9-719c0de9dee3.png">

**Comment by robinv85** [comment]
@anniegiang is this frontend or mobile app?
Maybe we need to split up some of this functionality between mobile web and native mobile app...?
Because the HTML5 geolocation works totally different from native apps functionality I think, and the pop-up for permission etc...

**Comment by anniegiang** [comment]
@robinv85 I thought this was for both mobile and desktop but yes we should slip it if the functionality is different

**Comment by robinv85** [comment]
@anniegiang Yeah I don't mean "mobile web" but "native mobile app" since that's a totally different way to integrate the location stuff as far as I know... it's just that the settings on the left in the image "allow while using the app" only make sense for a native mobile app.

The problem I think for web is also with the different flows, and whether or not the user is logged in with a registered profile, they might already have the location so we need to check that... otherwise it can be just once to allow location with htm5 API, and then we could save it or we could ask it again every time, depending what the use case is.

**Comment by Samdisha** [comment]
@anniegiang @robinv85  any updates to this issue?

**Comment by robinv85** [comment]
@Samdisha there were some discussions on Slack I think also with @Naraujo13 and @joshmorel and maybe others so maybe you can read those and add some feedback there

**Comment by vikjoshi** [comment]
I don't think can be complete until we finish https://github.com/FightPandemics/FightPandemics/issues/469

**Comment by joshmorel** [comment]
I asked about this in slack. For authenticated is it supposed to overwrite user's own location for filtering (e.g. if my location is New York City but I ask for Buffalo now share_with city "Buffalo" posts will be visible).

**Comment by joshmorel** [comment]
Will be resolved with #721
