### ISSUE TITLE
HB-Search keyword on people should get all the individual records having keywords matching name and/or about

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#1702]
1-User enters keyword to search : for example - the 
2-Click on People tab and get two records with the on about each record
3-Click on Filter and enter -San Jose , CA for location and click on Apply Filters
4-**Since the Individual 's first record checked on Don't show my address on profile , the first record is not in display as expected and the second record is on the top since Individual has San Jose , CA address**
5- Also see 4 more records have 'the' in the Name.  **Expect- These 4 news records should display on step 2.  Step 2 should have 6 records instead of 2 records** 
6- **if click x to remove the location , we come back on 2 records we have on step 2 which I expect to see 6 records.**
please see the GIF 

![People_search](https://user-images.githubusercontent.com/70918430/96827518-9baccc00-13ea-11eb-86b7-4141a54eeee5.gif)

**Comment by adorapham** [comment]
@Zaydme can you please review this one

**Comment by Zaydme** [comment]
this behavior was fixed in https://github.com/FightPandemics/FightPandemics/pull/1695 for **signed in** users.

---
For the unsigned we said that there will be only full word match **(full $text search)** when no location filter is selected **(because not using $geoNear, so using full $text search and NOT regex)** so a record must have at least one 100% match for whole word. So this is why results are less, While it can do partial match when location is known **(now it's using regex and NOT full $text because using $geoNear)** so there will be more results (even the ones not including a 100% match of the word).

_note that the highlighting might highlight half word, but the back-end only matches full word in that case (unknown location)_

**Comment by adorapham** [comment]
Agree with closed defect  after performing the validation on the fixed.
**not signed in**  , per DEV
For the unsigned we said that there will be only full word match (full $text search) when no location filter is selected (because not using $geoNear, so using full $text search and NOT regex) so a record must have at least one 100% match for whole word. So this is why results are less, While it can do partial match when location is known (now it's using regex and NOT full $text because using $geoNear) so there will be more results (even the ones not including a 100% match of the word).
![People_searchWorkforUnsignedIn](https://user-images.githubusercontent.com/70918430/96935567-305e0b00-1479-11eb-9018-07ee63710478.gif)

**signed in user**
![People_searchWorkforSignedIn](https://user-images.githubusercontent.com/70918430/96935883-d90c6a80-1479-11eb-8977-6cef819e25f4.gif)
