### ISSUE TITLE
Instant Email Notifications for Direct Messages

### ISSUE THREAD

**Issue by mannykary** [FightPandemics/FightPandemics#1741]
@Zaydme to add details on how to query for new DMs to send emails for.

**Comment by Zaydme** [comment]
Email notifications for DMs can be achieved by querying the `threads` collection, 
- looking for `participants.id` equal to user.id (`participants` is an array of objects, probably not the most efficient)

in the **matching** participant
- WHERE `newMessages` (`Number`) is greater than 0 
- AND `lastAccess` (`Date`) is older than whatever the "instant" emails delay is.
- IF `status` is "accepted", just send normal email about new message.
- IF `status` is "pending",  send email about "New message request".
- IF `status` is "blocked" OR "ignored" OR "archived" don't send any email.

in the **unmatching** participant, (which is the sender in this case, since only 2 participants in the array) you can get:
- `id` (Ref: User)
- `name` and `photo` (which should be up to date)
- `type` can be one of these `[ "Company", "Community", "Government", "Health care provider", "Individual", "Non-profit", "Other", "Startup", "University", ]`

### notes
- if you want the message content, you can query the `messages` collection for the last message with the `threadId` equal to the `thread._id`.
- you can also find the message status, which can be one of `["deleted", "edited", "sent"]`.
(Note that when the message is "deleted" the content will be `null`)
- Some messages, especially the first one have a postRef, which is the embed post in the message.
![image](https://user-images.githubusercontent.com/46847212/97929047-98a9c800-1d68-11eb-990e-83e369983bae.png)
so when the `status` is "pending" and you send an email about "New message request" you will need to include the `postRef.title` so the user can know what post they are getting contacted from (you can also get the `id`, `objective`, `content` and`createdAt` (which is the post creation date, not the `Message` document creation date))
- if message was sent from profile page, there will be no `postRef` even if it's the first message, so it will be a "New message request" email, but without `postRef`

**Comment by mannykary** [comment]
Currently in progress.

**Comment by shrutigupta1981** [comment]
https://featurenotifications.fightpandemics.xyz/post/5fb46a8ae50b38001183f07a

I didnt get any email for pending status. Just got one email for message thing after clicking on Accept button though send many messages. Please check.

**Comment by shrutigupta1981** [comment]
![image](https://user-images.githubusercontent.com/72843352/99467969-5948b300-28f4-11eb-99e3-8848523b0b9f.png)

**Comment by shrutigupta1981** [comment]
![image](https://user-images.githubusercontent.com/72843352/99468138-c8bea280-28f4-11eb-936d-3df560acb491.png)

**Comment by shrutigupta1981** [comment]
No timestamp in this messages and no email also generated for these messages
![image](https://user-images.githubusercontent.com/72843352/99468273-0f140180-28f5-11eb-9cf7-ea732aa1f020.png)

**Comment by shrutigupta1981** [comment]
Email generated for only single message 
![image](https://user-images.githubusercontent.com/72843352/99468327-2b17a300-28f5-11eb-99bf-dfb0da06200a.png)
![image](https://user-images.githubusercontent.com/72843352/99468374-4bdff880-28f5-11eb-98d4-f3c3cb6dce05.png)

**Comment by mannykary** [comment]
@shrutigupta1981 I can't really say if this is expected behavior without knowing the exact reproduction steps. but I will point out that the receiving user's inbox should not be open in your other browser session when you send a direct message to that user. Otherwise the user will be considered "online", and they will not get any email. I would recommend the following test cases be followed, and if the actual result deviates from expected, please note it in this ticket. Thanks!

### Case 1 - two users who have never communicated with each other - message from profile page
1. Open two separate browser sessions for two different users, and make sure that the receiving user is not on the DM inbox page.
2. From one of the users, send a message to the other user from their profile page (not a post)
3. Wait at least 10 minutes

Expected: The receiving user receives an email with the subject and body of `<user name> sent you a direct message request`

### Case 2 - two users who have messaged each other at least once - reply back in the inbox
1. Open two separate browser sessions for two different users, and make sure that the receiving user is not on the DM inbox page.
2. From one of the users, go to the DM room in the inbox for the receiving user, and send a reply back to the user.
3. Wait at least 10 minutes

Expected: The receiving user receives an email with the subject `<user name> sent you a direct message`, and the body should contain the direct message text.

### Case 3 - two users who have never communicated with each other - message from post
1. Open two separate browser sessions for two different users, and make sure that the receiving user is not on the DM inbox page.
2. From one of the users, send a message to the other user from one of their posts
3. Wait at least 10 minutes

Expected: The receiving user receives an email with the subject and body of `<user name> sent you a direct message request`, and the body should contain the title of the post.
