### ISSUE TITLE
Update styling for Symptoms Check for Desktop

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#175]
- [ ] Update current Symptoms Check UI's styling for desktop.

Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

- [ ]  Designs need to be pixel perfect

**Comment by agmaal1** [comment]
Hi, I've created a new branch to address this issue. feature/175symptomscheckstyling

**Comment by agmaal1** [comment]
@anniegiang @robinv85 @manualzuru   Since the symptoms check relies on the step wizard, I am not sure if what we want is to style differently the step wizard for the symptoms check or change the styles for the step wizzard itselves and therefore apply that styling in other parts that rely on it as the need help part. 

In other words, should I modify the styles directly in the stepwizard's components or overwrite the styling, without the wizard's component being modified, via styled(stepwizardcomponent)``?

**Comment by anniegiang** [comment]
@agmaal1 Thanks for starting on this!

**Comment by agmaal1** [comment]
@anniegiang @robinv85  I've styled step 1 and 2. Could you take a look to the changes in the branch before proceed with the rest of the steps? 

As we agreed, I'm doing it without overwriting the wizards components, but I'm not sure it that's the best way since leads to a lot of code repetition. Wouldn't be better to change directly in the wizard components styles to make them able to change depending on props? I mean this way:

implementing styles:
`export const SCAnswerButton = styled(AnswerButton)`
height: ${(props) => props.height?.mb ?? "5rem"}
 @media screen and (min-width: ${mq.tablet.narrow.minWidth}) {
    font-size: ${(props) => props.height?.dkt ?? "8rem"};
  }
`
applying custom styles:
<SCAnswerButton height={{mb:'5rem', dkt:'8.5rem'}}>Button content</SCAnswerButton />
`
I'm doing it inside the Symptoms check to avoid repetition, but wouldn't be better to do it directly over the wizard's components?
