### ISSUE TITLE
Update styling for Create User Profile for desktop

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#176]
- [x] Update current Create User Profile page styling for desktop.

Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

- [x]  Designs need to be pixel perfect

**Comment by Chimaobi-Johnson** [comment]
There seems to be no existing create user profile, unless you re talking about user profile?

**Comment by robinv85** [comment]
@Chimaobi-Johnson I think you're right, there probably isn't a page yet.
A while ago I added some redirection logic while updating the auth, so that will probably need to be extended to redirect to "create profile" at the right time, making the redirection part even more complex.
There is still a pull request in progress for the backend to create a user as well: #130 
And I think for the first version we should just use the email from the JWT token, edge cases such as Twitter which doesn't return an email or maybe Facebook profiles without email address, should probably be looked at afterwards how be can best approach that.

**Comment by T-Allen** [comment]
Although this issue pertains to desktop styling, might we add mobile styling as well? As @robinv85 said, there isn't a page for this yet, so I went ahead and made one and added it to the routes.
