### ISSUE TITLE
Switch Profile -> Individual profile user can EDIT/DEL the post, posted as an ORG and vice-versa.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1843]
As per the requirements mentioned in PR #1436 missed to be added in PR #1767 

"user should only edit or delete what is based on that profile- Indiv or org. If indiv, I can only edit or delete posts I made as an indiv.

If org, I can only edit or delete posts made by that org.

If user has more than one org, they have to be acting as same org that created post to edit or delete."

Need to add this missing functionality for 'Organizational Switch'

related to #1849 #1855

**Comment by joshmorel** [comment]
We we're going to tackle this 2nd after getting core "account switch" working because it was already working and we wanted to keep the original PR management.

This includes and should be done as one PR (cc @camba95 @Zaydme @ddveloper ):

1) Create post - skip the whole "as user/org" - just go right to post page for active account
2) Delete/edit post - don't show for non-active even if you are owner
3) Edit profile pencil - only show for active account

There are some others probably.

**Comment by rabbi08** [comment]
Just as an update the 'Comment' feature is working fine for both "ORG/Indivi". 
- The comments added by an individual -> cannot be edit/delete by their own ORG and vice -versa. Please see below GIF.

![ezgif com-gif-maker (61)](https://user-images.githubusercontent.com/67168400/99691456-413d7480-2a57-11eb-9977-4b0151cc4adc.gif)
