### ISSUE TITLE
not easy to tell difference between "offer help" and "need help"

### ISSUE THREAD

**Issue by ddveloper** [FightPandemics/FightPandemics#1942]
when I edit a post, though I can select "offer help" or "need help" it does not reflect on the resulting post
<kbd>
![image](https://user-images.githubusercontent.com/44758313/100307659-43259d00-2f5b-11eb-8b7e-391045f4f854.png)
</kbd>
same observation on the "Help Board", not easy to tell "offer" or "help" for each post
<kbd>
![image](https://user-images.githubusercontent.com/44758313/100307824-b0d1c900-2f5b-11eb-9383-e7166a2fc3fb.png)
</kbd>
propose a prominent icon on the post digest (below icon is for demonstration only)
<kbd>
![image](https://user-images.githubusercontent.com/44758313/100308826-2c347a00-2f5e-11eb-9fda-b297f45e61e5.png)
</kbd>
@CamilaArias

**Comment by adorapham** [comment]
@ddveloper . in edit post we can see whether the post is Offering help or Requesting Help. Please see if the below explain your concern.  when clicking on **...** to edit the post , the tab of requesting help in display because the post is created for requesting help type.  if you need more explanation , i can help out.  BTW, if you know it already and still think it need improvement, please consider this as an issue to get improvement 
![image](https://user-images.githubusercontent.com/70918430/100310156-694e3b80-2f61-11eb-8ff2-01cefc6e38ad.png)
on the help board, you can choose all posts (requesting help and offering help ) or you can select requesting help 
![image](https://user-images.githubusercontent.com/70918430/100310241-9c90ca80-2f61-11eb-8f88-aee264bd44ba.png)
the picture above, i think it is offering help
![image](https://user-images.githubusercontent.com/70918430/100310440-15902200-2f62-11eb-88e6-c990fe7e9af2.png)

**Comment by ddveloper** [comment]
just realize we have home page entrances user can choose "offer help" or "request help", so we may not need such a `prominent` icon, it could be just me but I think the "offer help" and "request help" should be much easier to access (like a label or icon on each post, or extract the "offer help / request help" option out of the `Filter`, so user can switch the view by single click instead of multiple clicks.

**Comment by ddveloper** [comment]
my bad @adorapham , I think you're right, this is more like for improvement, close this for now

**Comment by adorapham** [comment]
@ddveloper , that is fine, testers run into the same situation many times :)

**Comment by CamilaArias** [comment]
@ddveloper we have designs to implement this in the post card, but next time feel free to move the ticket to the new UI/UX Feedback project so we can tackle it :D
