### ISSUE TITLE
many words are not translated

### ISSUE THREAD

**Issue by ddveloper** [FightPandemics/FightPandemics#1945]
when switching to different lanugages, the `Switch Accounts` seems stay in English
test it on https://staging.fightpandemics.work/

![image](https://user-images.githubusercontent.com/44758313/100312380-09f32a00-2f67-11eb-8113-c2cab26a4bf8.png)

![image](https://user-images.githubusercontent.com/44758313/100313164-dc0ee500-2f68-11eb-8196-fc1cec5906c3.png)

**Comment by ddveloper** [comment]
some of them (e.g. the `Switch Account`) was due to Lokalise QA warnings?? (see below picture), others are code issue
![image](https://user-images.githubusercontent.com/44758313/100321401-79711580-2f77-11eb-925a-9cc45a42e3c8.png)

**Comment by adorapham** [comment]
@ddveloper , you can search the key on home page even the word is already translated.  also you can use translation channel to get help .  I log 2 defects one for developer :#1916 and one for myself #1852 (data fixed) so you can take a look
![image](https://user-images.githubusercontent.com/70918430/100375225-50c23d80-2fc2-11eb-80b6-031c3bbbe880.png)
for the warning , it is not blocking the display on the website because the software just check for grammar or spelling.
![image](https://user-images.githubusercontent.com/70918430/100375322-76e7dd80-2fc2-11eb-9cdf-ea22e4b2e17f.png)

**Comment by ddveloper** [comment]
Thanks @adorapham , this issue is duplicated with #1916 , I am closing this
