### ISSUE TITLE
[Desktop][STG] [Front End][BUG] Privacy Policy, Terms and Conditions, and Help Board did not translate to selected language.

### ISSUE THREAD

**Issue by ghost** [FightPandemics/FightPandemics#2136]
Environment:
macOS 10.14 Mojave
MacBook Pro (15-inch, Early 2015)
Browser: Firefox 78.6.1esr 
https://staging.fightpandemics.work/

Steps:
1. Navigate to https://staging.fightpandemics.work/
2. Click on the world icon on upper left corner of the horizontal navigation bar, and select French, or a different language
3. Navigate to the bottom of page ( footer)
4. Click on both Privacy Policy, and Terms and Conditions links, and observe each page’s translation
5. Click on “Help Board” located on the top of page within the horizontal navigation bar, and observe page’s post translation

Expected Behavior:
Privacy Policy, Terms and Conditions, and Help Board should be appropriately translated.

Actual Behavior:
Privacy Policy, Terms and Conditions, and Help Board did not translate to selected language. I selected French, and observed the English language.

https://user-images.githubusercontent.com/76545271/104430925-2a3d6f00-553c-11eb-92e9-422c056193b2.mov

**Comment by doheekim93** [comment]
Hi @Rebeccabeesknees, Privacy Policy and Terms of Conditions are left in English for legal reasons.  

We are also not translating the **contents** of what users are posting for various reasons. One of the reasons is that the message/intention expressed by the user may be lost in translation and another reason is that if a user reaches out to the post creator in French  (as an example) because they saw the translated version, but the post creator doesn't speak French, then there will be communication barriers.
We are going to implement an automatic translation (such as Google Translate) feature for post contents, but that is not implemented yet.
