### ISSUE TITLE
Clicking on "request help"  and then go to "show me postings from anywhere"  shows posts for "offer help" 

### ISSUE THREAD

**Issue by JayashreeSamantasinghar** [FightPandemics/FightPandemics#2220]
Clicking on "request help" for frontend  in staging and then clicking on "show me postings from any where " shows posts for 
"offer help"
<img width="960" alt="2021-02-14" src="https://user-images.githubusercontent.com/68357352/107881162-f1284f80-6e97-11eb-9b69-52f35dee1bbd.png">
<img width="960" alt="2021-02-14 (1)" src="https://user-images.githubusercontent.com/68357352/107881168-fd141180-6e97-11eb-9722-01d545c4ba27.png">

And Clicking on "offer help" in frontend and then clicking "show me postings from anywhere" shows posts for "request help"

**Comment by aditilamkhede** [comment]
@JayashreeSamantasinghar I think it's expected behavior. Person is requesting help, thus shown posts with "Offer Help". i.e. i,.e. a requestor is shown who all are offering help and then from there he can choose the relevant post for him/her and then he/she can contact the person who is offering the help.
@rabbi08 correct me if my understanding is wrong.

**Comment by rabbi08** [comment]
Agree with @aditilamkhede 
persons who are requesting help will be connected with those who are offering help and vice-versa.
Let me know if this makes sense or if there is some issues or concern. Thanks

**Comment by JayashreeSamantasinghar** [comment]
@aditilamkhede @rabbi08 
Thanks for clarifying me. May be I misunderstood.
