### ISSUE TITLE
Need descriptive error responses from the server for signing up 

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#225]
Ran into a vague response when trying to sign up: 
<img width="705" alt="Screen Shot 2020-04-30 at 5 40 36 PM" src="https://user-images.githubusercontent.com/42228386/80772838-da815980-8b0c-11ea-8f6f-8efa11412c42.png">

While in the terminal you can see that the specific reason for the 500 error is because the password is too weak
  - I was able to sign up after using a stronger password with capital letters and non-alphanumeric characters 
<img width="1440" alt="Screen Shot 2020-04-30 at 6 06 45 PM" src="https://user-images.githubusercontent.com/42228386/80772990-5da2af80-8b0d-11ea-806f-980c3caa710a.png">

**Comment by robinv85** [comment]
ah yes, good find, I forgot to handle that error case.
I added more explanation about the error handling in my PR https://github.com/FightPandemics/FightPandemics/pull/224/files while adding the fastify-sensible plugin which will also return a 500 error if something goes wrong.

There is still a to do in the code in the Auth0 component
````
// todo: check improving the error handling here, could also check & handle or pass the response message e.g.
/*
    data: {
      error: 'invalid_grant',
      error_description: 'Wrong email or password.'
    }
 */
```

because I noticed this erorr info wasn't used, I would prefer not to send just every error from Auth0 to the frontend so we have to handle every specific case accordingly, but we could also opt to use the statuscode e.g. 400 bad request to return also a 400 in that case, if possible.
