### ISSUE TITLE
User Story 2.1 - Issue 3: Individual user  be able to type in the pre-screening form with a single mouse click and the mouse cursor/pointer

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2328]

**Comment by hiran11** [comment]
@xJamesScott  User Story 2.1-Individual user  be able to type in the pre-screening form with a single mouse click and the mouse cursor/pointer. 

The asterik sign is left to next line rather than next to question mark . 

![image](https://user-images.githubusercontent.com/51660881/117062788-e2f90b00-acf1-11eb-94fb-c2cb3dc9e047.png)



https://user-images.githubusercontent.com/51660881/117062667-b5ac5d00-acf1-11eb-9f57-16eaca792a3c.mp4
