### ISSUE TITLE
Symptom Checker- Mobile- Highlighting Behavior for Multi-choice selections

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#357]
On questions where you are able to select more than one option like for below question: 

Actual Behavior: Currently, once I click on a symptom, it gets selected, moves down the list, and the next symptom on the list is automatically highlighted. 

Expected Behavior: 
1. Clicking on a symptom should highlight the symptom and its placement on the page should not change. 
2. Clicking on a highlighted symptom should un-select that symptom. 
3. highlighting or unhighlighting a symptom should not change its placement on the page. 

Tested on iOS Chrome browser v81

![image](https://user-images.githubusercontent.com/41554004/82019733-9b8af200-963c-11ea-956f-0927efa08bfc.png)

**Comment by snowiesuet** [comment]
Related to #304

**Comment by manualzuru** [comment]
@vikjoshi @snowiesuet

**Comment by vikjoshi** [comment]
@manualzuru that page is behaving pretty funky right now so think we should keep this open until we have the time to go back to it after MVP

**Comment by dhruvdpatel** [comment]
This issue is still active in the Mobile view. We need to fix following issues.

issue # 1 - Previous and Next Arrow buttons are overlapping with the symptom selections. (Mobile)
issue # 2 - When user clicks on a highlighted symptom to unhighlight, it does not remove the blue highlight. (Mobile)
issue # 3 - Once Symptoms are selected, next button is not functional. (Mobile)

Once this three issues are fixed, mobile verification can be moved to the next.

**Comment by dhruvdpatel** [comment]
Bugs are opened for this ticket separately. Closing it.
