### ISSUE TITLE
Improve Webapp's performance speed

### ISSUE THREAD

**Issue by snowiesuet** [FightPandemics/FightPandemics#361]
![image](https://user-images.githubusercontent.com/3907305/82064781-39150e80-969b-11ea-8888-a33339bafcb7.png)

Our current website's performance speed has a very low score in Google's [audit](https://developers.google.com/web/tools/lighthouse/) tool. We should try to fix these issues as our team and project get bigger. 

Some of the issues we should consider fixing :
[ ] Serve static assets with an efficient cache policy
[ ] Use CDN when possible (fonts)
[ ] Convert icons to custom font
[ ] Other suggestions from Google's audit:

![image](https://user-images.githubusercontent.com/3907305/82065578-47aff580-969c-11ea-873c-6fe11f578024.png)

**Comment by acsteves** [comment]
Hi @snowiesuet @anniegiang just confirming -- this is not a launch blocker, but should be treated as an enhancement after launch, yes?

**Comment by anniegiang** [comment]
Correct performance is not a priority right now and this issue has the "enhancement" label.

**Comment by snowiesuet** [comment]
Yes, this is currently on hold.

**Comment by robinv85** [comment]
@anniegiang and @snowiesuet maybe I was a bit too explicit about improving performance
Performance shouldn't be treated as an after thought, we should always keep it in mind when developing, but we also don't want to do "premature optimization".

In the case of the icons, like I've said, we could also use another approach similar to what Facebook did in their latest update and use SVG components (rendering `<svg />` tags from React components instead of now rendering `<img />` tags with a src attribute. This also has the added benefit that we don't need to recreate a new font whenever there is a change to an icon (unless we add this automation in our workflow), and it might be even better for performance when the webpack bundles are optimized into chunks. More info about this here https://engineering.fb.com/web/facebook-redesign/

For the fonts, I think we don't even have the fonts correctly imported at the moment. There are 3 custom font, one didn't seem to work via npm install, and I question if we really need 3 custom fonts, one of them is currently only used on some buttons. This might have a big impact on performance.

There are more useful performance improvements that are explained here on this page https://web.dev/react/

**Comment by joshmorel** [comment]
Compression is done - the easiest win and biggest impact to performance as I expected - #1076 .

We should break other items out into specific (lower priority) tickets and close this one. 

1. Webpack chunk optimization 
2. Importing SVGs instead of using img tag
3. Import fonts via CDN

**Comment by joshmorel** [comment]
Closing for:

PR/issue:
#1076 / #1075 

Issues:
#1078 
#1079 
#1080 

After these are done we can re-evaluate and look into further options.
