### ISSUE TITLE
Requirements for User Sign up/Login and Completing Profile 

### ISSUE THREAD

**Issue by jjho** [FightPandemics/FightPandemics#39]
- In order for someone to create a post, they must be a) have an account, and b) has signed in.
-New user is able to create a new account by the following ways:
1) typing in email address and password. This method of creating user account will be verified by sending a verification email to the email address.
2) sign in via alternative social media account or Gmail account
-Store user account with username, user unique ID, and password (password encrypted?)

<img width="245" alt="Screen Shot 2020-04-02 at 11 25 31" src="https://user-images.githubusercontent.com/742412/78284744-b4987300-74d4-11ea-9eac-a33f0dbe5fcc.png">

-After new user account is created, go to next screen "Complete your Profile"

<img width="255" alt="Screen Shot 2020-04-02 at 11 28 26" src="https://user-images.githubusercontent.com/742412/78286199-ad259980-74d5-11ea-9b7f-ec8a2b6c0031.png">

-Create field to enter username (required field). This can be their true name or alias. Allow maximum 100 varchar including spaces and hyphens. Do not allow other symbols or numbers.
-Create field to enter country name (required field). Only allow names of real countries.
-Create field to enter neighborhood name (not required). Only allow real neighborhood names from designated country from previous field.
-Create checkbox for "I am traveling" (not required)
-Create checkbox for "Don't show my neighborhood" (not required)
-Create I need "medical help" OR "Other help" (required to check one or the other)
-"Complete Profile" button to complete save input and move on to next page. Only allow to move on to next page if they check the Terms and Services box.

**Comment by manualzuru** [comment]
I think it looks good @jjho, However, I think isn't complete and the flow isn't correct. @robinv85 maybe it's 1 ticket because the whole logic seems to me like isn't complete as it's important to say that this screen is the same for login/register and the logic is that if the user isn't already in our data base, then it creates a profile. otherwise, it logs you in.

1. username can be interpreted as @ManuAlzuru and it shouldn't be username, it should be user_name which should be at least 2 words and a minimum of 6 characters. For instance, the first name with 3 letters, space, last name with 2 letters could be validated and approved.

Reason: On the UI we are showing Name and Last name (minimum) we need to keep this social media professional and reliable. I don't want to interact with @misteryo user I want to interact with @Robin Venneman. 


2. If the user signs-up with social media, grab the relevant info locally and show that data in the complete profile screen. 

Note: The product team should see what are the fields available in Auth0 API and how to match the fields with the UI and provide our engineers with the right links. Here is the link to everything that is available out of the box from Auth0: [https://auth0.com/docs/connections/identity-providers-social)](https://auth0.com/docs/connections/identity-providers-social)

**- FB Auth0 documentation:** [https://developers.facebook.com/docs/facebook-login/permissions](https://developers.facebook.com/docs/facebook-login/permissions)

![image](https://user-images.githubusercontent.com/35108827/78308101-d67f0d80-7547-11ea-847a-618265d773be.png)
![image](https://user-images.githubusercontent.com/35108827/78308119-e5fe5680-7547-11ea-804f-513891d513cb.png)

Therefore, our user_name = FB_first_name+(space)FB_middle_name+(space)+FB_last_name
or 
user_name = name

Note: it could be only user_name = FB_name but it depends on how FB passes that or what they mean with that. 

So the same idea applies for all the other fields, we need to map them with our DB.

**- TW Auth0 documentation:**[https://auth0.com/docs/connections/social/twitter](https://auth0.com/docs/connections/social/twitter)

Fields available: [https://developer.twitter.com/en/docs/labs/overview/whats-new/fields](https://developer.twitter.com/en/docs/labs/overview/whats-new/fields)

**- Linkedin Auth0 documentation:**[https://auth0.com/docs/connections/social/linkedin](https://auth0.com/docs/connections/social/linkedin)zx

Fields available (please see also check full profile fields):[https://docs.microsoft.com/en-us/linkedin/shared/references/v2/profile/basic-profile?context=linkedin/consumer/context](https://docs.microsoft.com/en-us/linkedin/shared/references/v2/profile/basic-profile?context=linkedin/consumer/context)

**- Google Auth0 documentation:**
[https://auth0.com/docs/connections/social/google](https://auth0.com/docs/connections/social/google)

**Comment by anniegiang** [comment]
@manualzuru @robinv85 Is this issue still relevant?

**Comment by robinv85** [comment]
I think the requirements here are mostly clear except for some details like for social media linking
and in case we don't have an email from a social media channel it might make some things more complex

**Comment by robinv85** [comment]
@indirabhowmick @manualzuru can this ticket be closed or is it still used? I will continue on this flow and finish user creation and related issues to auth flow

**Comment by indirabhowmick** [comment]
@robinv85 - sounds good. I just closed the issue. Thanks
