### ISSUE TITLE
User Auth - Confirmation Email 

### ISSUE THREAD

**Issue by pthoma14** [FightPandemics/FightPandemics#493]
**Success Criteria:**
- Sendgrid api should be used as the transactional email service

- The backend needs to be connected with email server

**Comment by joshmorel** [comment]
Design: 

![image](https://user-images.githubusercontent.com/10546720/83023660-326f8b00-9ffb-11ea-868d-fcb9a74f40e1.png)

**Comment by joshmorel** [comment]
@pthoma14 @indirabhowmick  This seems to be working in staging so you can test there. There's no code change in our app just a template that we'll be storing in a different repo. https://github.com/FightPandemics/FightPandemics/Auth0

The "please verify your email" page is being improved currently.

**Comment by joshmorel** [comment]
@pthoma14 @indirabhowmick 

The [related code is in the other repo](https://github.com/FightPandemics/Auth0/pull/2
) for both account confirmation & welcome email. They are also saved in our Auth0 dev, staging & prod Auth0 environments. 

The review environment - because it has the variable subdomain (_featureXYZ_.fightpandemics.xyz) is not going to work for these so in Auth0 I disabled the welcome email and left the verification email to the default. If we want to user test changesto these emails post-launch we'll need to do it in staging.

If all seems good close this ticket.

**Comment by robinv85** [comment]
@pthoma14 @indirabhowmick @joshmorel is this in progress? if so, can probably be updated on the project tracker since it's still in the first "new:" column right now

**Comment by joshmorel** [comment]
@robinv85  I put it in review. Once I get confirmation from  @indirabhowmick that the updated verification email (+ welcome email) are okay we can move it to done.

**Comment by indirabhowmick** [comment]
@joshmorel @robinv85 - I did get the confirm your email address mail, but when I click on confirm account button in the email, it is throwing  404 page not found an error.

**Comment by joshmorel** [comment]
@indirabhowmick Hmm. It was working before. Wonder if it has to do with SendGrid? I will look into tomorrow.

**Comment by indirabhowmick** [comment]
@joshmorel I was able to test the functionality this morning. Thanks!
