### ISSUE TITLE
[Desktop][Mobile] Sign In/Up screen | facebook icon

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#496]
env: https://staging.fightpandemics.work/
Steps:
1. Open application and go to the Sign In/Up screen
When I open this screen for the first time Facebook icon is too small (look at the screenshot below).
When I open Sign In/Up page for the second time facebook icon has a proper dimension.
![Screen Shot 2020-05-27 at 16 14 02](https://user-images.githubusercontent.com/21987083/83031682-256f8d80-a035-11ea-89f9-aa6fc634c09f.png)

How to reproduce: remove cookies and cache

**Comment by manualzuru** [comment]
https://github.com/edent/SuperTinyIcons

Here we can find super tiny icons that are optimized for web.

**Comment by robinv85** [comment]
issue seems not fixed, SVG icons have been replaced but the small icon is still showing

**Comment by CeesWang** [comment]
![facebook-icon-bug](https://user-images.githubusercontent.com/33577774/83584273-9e2e8800-a514-11ea-9e10-2b8c3ef1f648.gif)

The facebook icon does not show up correctly on initial view but it shows up correctly after going to signup and back. This is the same with the desktop version

**Comment by manualzuru** [comment]
@CeesWang did you take this or should we put this in New? To me it doesn't seem fixed, it has a weird bug.

**Comment by gullwings13** [comment]
Sorry I thought this resolved. I will try to figure out why this might be happening

**Comment by gullwings13** [comment]
The issue affected any icon. The issue is fairly intermittent, but I was able to reliably recreate the issue in firefox, in the end, it seems to be related to the width of the text in the button. Decreasing the left and right padding seems to alleviate the issue.
![happens with google icon](https://user-images.githubusercontent.com/629700/84948701-191da400-b0ba-11ea-938f-60a98d4e044c.PNG)
![related to text width](https://user-images.githubusercontent.com/629700/84948704-19b63a80-b0ba-11ea-9ef1-53b5e04b03a4.PNG)
