### ISSUE TITLE
Check for null doc when throwing notFound errors

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#513]
We have code like this in several places https://github.com/FightPandemics/FightPandemics/blob/f48489ac7503b140d0f5de399a0c6e4b95bba989/backend/lib/endpoints/posts.js#L175

```javascript
const [userErr, user] = await app.to(User.findById(userId));
if (userErr) {
    throw app.httpErrors.notFound();
}
```

But if the doc isn't found `userErr = null` and `user = null`. We should check for null user as well in the condition.

@robinv85 I recall you referencing we should log errors in these kind of scenarios. Should that be included in the resolution to this issue?

**Comment by robinv85** [comment]
Yeah I'm not completely sure what the Mongoose API can return here, for example `User.findById()` and similar calls... but I suppose that `userErr` here can be different things, not just "not found"
So in that case I think we shouldn't even return `404` since it can rather be a  `500` 
And still if `user === null` then definitely a `404`.
And in the case of `userErr` indeed it seems best that it's in our logfile so we can detect problems. Otherwise this just gets ignored.

**Comment by joshmorel** [comment]
I think any errors sent back by Mongo should be considered 500 errors then? 

So it should be:

```
if (userErr) {
 // do something w 500 error 
} else if (user === null) {
   throw app.httpErrors.notFound();
}
```

But the do something w 500 error does this change since were using sentry?

**Comment by idjevm** [comment]
@BMariscal Should we reopen this issue?
