### ISSUE TITLE
[Desktop][Mobile] Feed | Post Creation | Visibility section

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#523]
env: https://staging.fightpandemics.work/feed
Steps:
1. Open app and go to the Feed screen
2. Create a post as an individual
3. Screen opens and visibility is **City**.
According to Figma design it should be Anyone:
"The post will be visible to" Anyone | Forever
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed034d492a787b8225c0b08
@TiagoaTavares are we going to change dropdown menu? In figma we have:
![Screen Shot 2020-05-29 at 14 27 45](https://user-images.githubusercontent.com/21987083/83259580-9b503200-a1b8-11ea-81ec-b49647d6b58c.png)
![Screen Shot 2020-05-29 at 14 27 54](https://user-images.githubusercontent.com/21987083/83259583-9d19f580-a1b8-11ea-8aa7-3a0c904cb5a8.png)

**Comment by TiagoaTavares** [comment]
- Change to Figma Design !

- Regarding to: "Anyone" | "Forever",
we should change to: "Worldwide" | "Forever" 

@galeza , one note:  follow figma instead zeplin for MVP launch ...  :)

**Comment by galeza** [comment]
Hi @TiagoaTavares ,

Ok. We will change to: "Worldwide" | "Forever" by default
+ drop down menu like in figma.

Thank you!

**Comment by TiagoaTavares** [comment]
@galeza what's your forecast date to close this issue? :)

**Comment by galeza** [comment]
Hi @TiagoaTavares 
I don't know if we have resources to fix that. This issue is tagged: MVP - Release 1 so I think it should have priority.

**Comment by TiagoaTavares** [comment]
@idjevm ... It is "Worldwide" | "month" ! not "forever" ! 
--> https://github.com/FightPandemics/FightPandemics/issues/523#issuecomment-637720525

**Comment by galeza** [comment]
Hi @idjevm 

#605 I asked @Yu-Alexa-Zhao about correct spelling and dropdown options

**Comment by TiagoaTavares** [comment]
> o (in my city, in my state, in my country, worldwide) (forever, for a month, for a year, for a day).

For now, focus on another issue .. This doesn't influence the functionality...

**Comment by galeza** [comment]
Hi @TiagoaTavares @idjevm 

Just a question. I checked data model and we don't have "state" option:
![Screen Shot 2020-06-05 at 19 10 04](https://user-images.githubusercontent.com/21987083/83906063-20ac8700-a763-11ea-98b3-3f46923d746d.png)
What do we insert into db while selecting this option? Should I check it with data engineers?

**Comment by joshmorel** [comment]
Until we set up some kind of data model process again the source of truth is the master branch model files - e.g.   https://github.com/FightPandemics/FightPandemics/blob/master/backend/lib/models/Location.js

We can decide about that post soft launch once we've stabilized a bit.

The two related PRs for this - we discussed in Slack with Manu - the designs weren't updated, can you ask someone?

https://github.com/FightPandemics/FightPandemics/pull/403
https://github.com/FightPandemics/FightPandemics/pull/407

I don't think we should include "In my neighborhood" as filter because many users might not have it and then the post may not reach enough people. It should be a discussion post MVP.

@galeza I think these two issues should be closed for now. I'll find the discussion in slack and message you.

**Comment by galeza** [comment]
Hi @joshmorel,

For now I'm closing #523 and #605

**Comment by galeza** [comment]
As stated in the PR #603 comments: 
Default should be: City - Month

**Comment by joshmorel** [comment]
This is resolved right @galeza ?

**Comment by galeza** [comment]
Yes. I'm closing this issue
