### ISSUE TITLE
[Desktop][Mobile] Sign In | password empty | internal server error

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#538]
env: https://staging.fightpandemics.work/auth/login

Steps:
1. Open Login screen, 
2. I choose email from a dropdown menu (chrome auto complete)
3. Password is empty
4. Button Sign In is enabled
5. Click Sign In button 

Error: Internal server error: xhr.js: POST https://staging.fightpandemics.work/api/auth/login 500

{statusCode: 500, error: "Internal Server Error", message: "Internal Server Error"}
error: "Internal Server Error"
message: "Internal Server Error"
statusCode: 500

![Screen Shot 2020-05-31 at 19 29 07](https://user-images.githubusercontent.com/21987083/83358663-4dccf400-a375-11ea-8692-6964cd8d7e6e.jpg)
![Screen Shot 2020-05-31 at 19 11 32](https://user-images.githubusercontent.com/21987083/83358665-502f4e00-a375-11ea-948c-8aada0ff3946.jpg)

**Comment by robinv85** [comment]
Hey @galeza thanks for reporting, but the client-side validation hasn't been implemented for that page so maybe this is some premature testing.

I will close this for now since I'm working on that and I want to prevent too many confusing tickets 
there is an open PR #409
and there is a ticket #369

So i'm going to re-implement that with the use of the react form library that we are now using
