### ISSUE TITLE
[Desktop][Mobile] Create Profile screen | refresh button email is empty

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#539]
env: https://staging.fightpandemics.work/create-profile

Steps:
1. Open login screen
2. Enter your email and password. Press Sign In button
3. Create profile screen is open with login 
4. Press refresh button
Email is empty:
![Screen Shot 2020-05-31 at 19 40 13](https://user-images.githubusercontent.com/21987083/83358844-9802a500-a376-11ea-9a97-454d2bb015e7.png)

![Screen Shot 2020-05-31 at 19 44 43](https://user-images.githubusercontent.com/21987083/83358929-32fb7f00-a377-11ea-89e7-46617ed42944.png)

**Comment by robinv85** [comment]
Hey @galeza thanks for reporting, this was actually intentional as the requirements weren't clear and I wanted to focus on MVP functionality

The reason this happens is because if you refresh, the token and the email is in the application state (currently redux) but this is not persisted in local storage or something similar.

We don't went to store this just in local storage because it has security issues to just save a token there without the user knowing they are still logged in.

The possible solutions for this are 
- add redirect back to login page or home screen but this also makes the whole redirection logic more cluttered and complex
- store the email and possibly even the token also in the URL
- store the token and also the email in session storage is probably best, this is persisted even after refreshing the tab, we just have to make sure this is no security or privacy risk etc. https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage so i considered that out of scope for MVP

**Comment by omarzoghayyer** [comment]
@robinv85 should we close issue for now?

**Comment by idjevm** [comment]
Seems like this issue was a misunderstanding. The expected behaviour is to return you to the homepage if you refresh.
