### ISSUE TITLE
close icon not vertically aligned with text on cookie banner

### ISSUE THREAD

**Issue by stavares843** [FightPandemics/FightPandemics#583]
flow
- open https://staging.fightpandemics.work/ on a anonymous browser
- close icon not vertically aligned with text on cookie banner

<img width="1740" alt="Screenshot 2020-06-04 at 00 38 22" src="https://user-images.githubusercontent.com/29093946/83699824-fe005e00-a5fc-11ea-88a0-a954de777604.png">

Chrome

**Comment by idjevm** [comment]
Hey @stavares843, I could take on this bug. However, I am wondering if we are taking into consideration lower resolution screens, as I noticed that the close button will stay sort of attached on the top rather than being always centered. 
This is what I did for now. 
![image](https://user-images.githubusercontent.com/25408660/83808467-d18f2500-a682-11ea-98fa-7d99ce7867e2.png)

However, if I zoom, this happens, is that the expected behavior, or it should always be centered? 
![image](https://user-images.githubusercontent.com/25408660/83808552-f97e8880-a682-11ea-97cf-e64533fbc4fa.png)

**Comment by stavares843** [comment]
not sure, can you tag product or design team about this?

**Comment by manualzuru** [comment]
Honestly, I think that what you are proposing is fine @idjevm. Go for it!

**Comment by Yu-Alexa-Zhao** [comment]
HI design team here! I think it is okay if the close icon is not vertically centered on the banner. The way it is right now (on top right) seems good to me (i.e., like in a browser, the close button is always on top instead of being centered) if it makes sense :-)

**Comment by idjevm** [comment]
Alright, so I think I just should change this -> 
![image](https://user-images.githubusercontent.com/25408660/83847157-c5828200-a6d9-11ea-8c10-2c93442042b5.png)

to look like this originally if the screen resolution is high (i.e the text fits in the screen without having to have a second line)-> have the text well centered basically @Yu-Alexa-Zhao.
![image](https://user-images.githubusercontent.com/25408660/83847332-0b3f4a80-a6da-11ea-962f-01afa2ad7416.png)
