### ISSUE TITLE
User login error - check email not verified first

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#614]
If I try to login without verifying my email I get this error:

![image](https://user-images.githubusercontent.com/10546720/83945293-b97cea00-a7d7-11ea-84c7-1f2c21a9f636.png)

Due to:

```javascript
      const { email_verified: emailVerified } = auth0User;
      const { payload } = app.jwt.decode(token);
      const userId = payload[authConfig.jwtMongoIdKey];
      if (!userId) {
        throw new Error("no mongo_id found in JWT");
      }

```

Should we check for the 4XX error first similar to `POST users/` before the 5XX error:

```javascript
      const { email, email_verified: emailVerified } = user;
      if (!emailVerified) {
        throw app.httpErrors.forbidden("Email address not verified");
```

**Comment by robinv85** [comment]
hmm ah yeah that's perfectly possible, guess I didn't test this enough, getting quite complex to get the steps right,  this one should be fixed first

**Comment by robinv85** [comment]
yeah after thinking about it more, i don't think this makes sense, users are able to log in and they get an access token (JWT) but they can't do anything except for confirming emails and creating user etc. before they can do anything else, so seems like this can't be right, maybe it's another problem / solution that's needed for the error?

**Comment by robinv85** [comment]
Ok so I think this is because originally I thought we shouldn't add the mongo_id on the Auth0 side until the email is verified, see https://github.com/FightPandemics/Auth0/blob/master/rules/mongo_id.js#L2
and then I added the error handler to prevent invalid Auth0 configurations
so now this means if you first sign up, and then you log in again before verifying the email, this error also returns, so we have to think about that, maybe just remove the email verified from the Auth0 script and make sure the check happens in our side

**Comment by adisen** [comment]
What's up with this?
