### ISSUE TITLE
[Desktop][Mobile] Create User profile screen | logo is disabled

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#630]
env: https://staging.fightpandemics.work/create-profile

Steps:
1. Sign Up - confirm email 
2. Go to Sign In screen and you'll be redirected to Create User Profile screen.
3. Click logo
Logo is disabled. On all other screens logo redirects user to the home/main page.
In case of Create User Profile screen - is it allowed to quit this screen (press logo) and go to the home screen?

![Screen Shot 2020-06-07 at 13 48 07](https://user-images.githubusercontent.com/21987083/83968360-ed840800-a8c8-11ea-9245-9af0acb04ed6.png)

**Comment by robinv85** [comment]
ah, good point, this is not really because the logo is "disabled" I think
I made it in such a way that the redirection logic will redirect you to the create-user profile if you are logged in and account is not active yet.
otherwise this might get even more complex, because some routes are available for both logged-in and not-logged-in users, so that means we cannot use the `isAuthenticated` check but also need to check if user exists to enable & disable certain features.
The whole auth flow is just very complex because it exists both in Auth0 for signing up and logging in, and in our own database to "create a profile".

**Comment by galeza** [comment]
I'm closing this issue. Work as design
