### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by umerhassan** [FightPandemics/FightPandemics#642]
![image](https://user-images.githubusercontent.com/33638819/83990310-753c3780-a906-11ea-8d27-b22167d10063.png)

SSL Certificate is not configured properly on the website.

**Comment by idjevm** [comment]
@mannykary @manualzuru This probably has to do with the things you guys have been doing right?

**Comment by joshmorel** [comment]
No this is because this image is served over http. It's a mixed content warning

![image](https://user-images.githubusercontent.com/10546720/84035962-8c147580-a96a-11ea-83fa-f8cea803cd9b.png)

This is logo for sourced by pandemics. I can change to https and I think it will work but really we should be storing this on S3 instead especially now that we are switching emails to Amazon SES (instead of SendGrid)?

Also, for avatar images they are external links so this still may occur, also for avatars ideally it would be an upload and we store to S3 instead of linking externally? Definitely can fix post go-live.

**Comment by joshmorel** [comment]
#652 fixes but only for Sourced By FP. When new users add avatars, if we're just storing a URL then well we have no control over this.

We'd need to upload images ourselves to S3. Probably a good idea but can be done post-MVP.

**Comment by robinv85** [comment]
yeah definitely cannot store an external URL as image, I think we can close this ticket @joshmorel @umerhassan ?

**Comment by joshmorel** [comment]
I think we should close this ticket as is. But we need a plan/ticket for updating avatars and storing photos. Should we create a ticket for v1.1 milestone or are you currently working on this as part of edit profile @robinv85?
