### ISSUE TITLE
Skip button is missing and submit button is not working

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#688]
Steps to replicate
1. Go to Need help
2. Press next, go to step 2
3. Press next, go to step 3

- [ ] The submit button validates but also has to redirect the user to the feed after the users presses it.

![image](https://user-images.githubusercontent.com/6276256/84418095-44287380-ac34-11ea-970c-344b3ad0947b.png)

- [x] Create a skip button following the same steps as above. It should look like the one similar to the one on the link https://staging.fightpandemics.work/offer-help#Step3
- [x] Skip must redirect the user to the feed.

**Comment by omarzoghayyer** [comment]
@robinv85 What do you suggest regarding this? should we work on it now?

**Comment by idjevm** [comment]
@ppagarawal I marked the create skip button as resolved since that will be resolved by #563 once it is merged. I think we can have this issue entirely for the submit button and validation. However, based on previous conversations, I don't think the API is set yet on the backend handle the submit button. I remember talking about this a few weeks ago. @robinv85 If I am not mistaken, the validation for this is not yet implemented right? also, the endpoint to receive the data is not ready yet I believe.

**Comment by idjevm** [comment]
I do remember that I offered to simply have the submit button redirect to the feed for the time being. But I think there were a few other conversations that happened that stopped me from doing that.

**Comment by galeza** [comment]
Submit button: this is duplicate
issue: https://github.com/FightPandemics/FightPandemics/issues/615 with a discussion how submit should work

**Comment by idjevm** [comment]
I agree with @galeza. Let's close this issue but move the conversation to #615 since this issue has been already opened for some time. 

If you guys think it should be open, please feel free to reopen it. 

@omarzoghayyer take a look to #615 for more context.
