### ISSUE TITLE
Header footer issue for feed

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#764]
Please correct the header and footer for feed. 
- [x] Header is on top and fixed
- [x] "Feed" text is on top and is scrollable
- [ ] footer background is transparent

**Comment by jyclam** [comment]
@ppagarawal @idjevm 
So the "Feed" text is actually a single tab from a tab bar (the rest of the tabs are temporarily disabled.) 

I've reenabled the other tabs to demonstrate:

![Screen Shot 2020-06-20 at 7 55 46 PM](https://user-images.githubusercontent.com/26049767/85215608-17f5ac80-b330-11ea-81d2-2ea0051f0fe6.png)

Are we intending to keep both the tab bar and the header bar for mobile view? I'm asking because it seems like they kind of achieve the same thing.

**Comment by ppagarawal** [comment]
@jyclam Please disable the other tabs. They were intentionally disabled.

**Comment by jyclam** [comment]
@ppagarawal Right will do, I only enabled them to take a screen shot.

I found designs in Zeplin with both the header bar and the tab bar, so that answers my question above.

https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed565218587a93f917fdb89

@ppagarawal When you said '"Feed" text is on top and is scrollable', do you mean that the tab bar should scroll away too?

**Comment by ppagarawal** [comment]
For this release, yes

**Comment by jyclam** [comment]
PR submitted. I'm not seeing the transparent background issue. I do find it hard to even see the footer in the feed due to the infinite scroll.

**Comment by idjevm** [comment]
@ppagarawal I believe that we wanted to have it as it was before but I was checking and the footer has kinda always been at the bottom of the page during scrolling. We should decide whether we want that, or just have it fixed OR completely remove it and add those links to the sidebar.

**Comment by idjevm** [comment]
For me, the sidebar makes more sense. @jyclam what do you think ? '
