### ISSUE TITLE
Improved duplicate email sign-up error handling

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#772]
**Update from @joshmorel**:

This error occurs because the email is already associated with a email/password or prior social auth sign-up using the same email. 

This should not be too commonly encountered by normal users so not soft launch critical but a better error reporting would be ideal. E.g. check if email exists at attempted sign-up & warn them before they go through whole create user process.

Eventually we aim to implement account linking #781 

**Original**:

Please note that my userid is my email 'rabbi08@gmail.com'.

Following error is displayed when Sign in/sign up using 'Linkedin'

Create user failed, reason: Validation failed: email: Error, expected `email` to be unique. Value: `rabbi08@gmail.com`

Please note my userid from Google with same email is working.

PFA the screen captured with  the steps.
[Screen Recording 2020-06-21 at 7.39.29 PM.zip](https://github.com/FightPandemics/FightPandemics/files/4810542/Screen.Recording.2020-06-21.at.7.39.29.PM.zip)

**Comment by idjevm** [comment]
I logged in with my LinkedIn account on staging, and it seems to also be working fine. I am not sure if it has to do with your linkedin settings? did you authorize when it asked you @rabbi08 ? @joshmorel @robinv85  not sure if it is happening to all users, but for my end everything works fine..

**Comment by joshmorel** [comment]
Hi @rabbi08 - this issue comes from a requirement that email must be unique - if you add a google account that uses xyz@gmail.com and a linkedin account that uses xyz@gmail.com you will get the error. We plan to add auth0 user account linking functionality - https://auth0.com/docs/users/concepts/overview-user-account-linking - for this case but we're not considering it launch critical, however, as this is something we don't expect normal users to encounter, unlike people doing QA.

We should create a new issue for the feature but in the interim we could create a friendlier message... "This email is already in use. Try signing in with email & password or the other social account you used".

**Comment by rabbi08** [comment]
Linkedin integration is working. Agree with @joshmorel, to display user friendly message.

**Comment by rabbi08** [comment]
Closing this issue and will track the #781  . Thanks
