### ISSUE TITLE
Have users' posts show up on profile

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#824]
MVP-Critical: As a user, if I go to my individual profile page, under "My Activity" I should see the posts that I've created 
![image](https://user-images.githubusercontent.com/41554004/85789133-e8092900-b6e2-11ea-88a1-dc7caec94577.png)

Post-MVP Launch: Activity should also show any posts that the user has liked or commented on 

B/E Ticket that is complete: https://github.com/FightPandemics/FightPandemics/issues/811

**Comment by kylejvh** [comment]
Just wanted to verify that I understand correctly:

The `?skip=0` query string is used to tell the database to skip the specified number of documents in a response. It looks like the backend sets this to zero by default if nothing is specified. So in this situation, I can safely remove it from the posts get request, which is what I ended up doing. 

Am I getting this right?

**Comment by joshmorel** [comment]
Yeah I think you can omit this in the query string

**Comment by vikjoshi** [comment]
Hmm @idjevm , is this something you may know the answer to?

Also, @kylejvh , just a note from @joshmorel on logic for this feature. you can set (authorId={ME})

**Comment by kylejvh** [comment]
@joshmorel Maybe you can explain the (authId={ME}) bit? I saw there was talk about maybe making more endpoints for this in Slack, but I'm not seeing any backend code that will support this.

Also, do you have any input on the post activity limit? I left it at 5 for now but I see there's support for to fetch with no limit, maybe we can add pagination as a post MVP feature.

**Comment by idjevm** [comment]
@joshmorel I think @Naraujo13 will also have some insight on this. 

And as for the input post activity limit, that's fine kyle, I merged your PR, and now let's have QA and PMs test it and we can revisit later as needed. We def would want to add pagination, not sure if that is something the team is looking for for the soft launch, @vikjoshi should have more input on that. So far looks great to load the latest 5 posts under your profile.

**Comment by Naraujo13** [comment]
> @joshmorel I think @Naraujo13 will also have some insight on this. 
> 
> And as for the input post activity limit, that's fine kyle, I merged your PR, and now let's have QA and PMs test it and we can revisit later as needed. We def would want to add pagination, not sure if that is something the team is looking for for the soft launch, @vikjoshi should have more input on that. So far looks great to load the latest 5 posts under your profile.

Yeah, skip defaults to 0 and limit to 5 if none is passed. Also, passing -1 as limit turns off pagination.

About the feature itself, probably @vikjoshi probably has more input on that, but the idea on profile was to display everything, wasn't it?
Ideally we would paginate it, but to not overload with this additional frontend task we would use everything at soft launch.

One thing I am curious is about the post sorting. Since the endpoint `GET /posts` was developed thinking about the feed, it returns the posts sorted by distance to the current logged user. So by using the same endpoint for the profile, we will see the user posts sorted by distance to who is currently logged (so closest to farthest instead of the 5 latest).

This is probably not a problem for soft launch, but if the idea is to sort by most recent in this case, we probably need to add that logic to the endpoint also (shouldn't be hard)
