### ISSUE TITLE
Recent POST is not added at the top for the respective user (ON HOLD)

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#875]
1. Open "https://staging.fightpandemics.work"
2. Login using valid email/password
3. Navigate FEED -> Create POST
4. Enter the details for the POST and click on POST, to create the POST.

Issue: You will observe that POST is created successfully but it is not displayed on top. 
P.S attached screen recording.

https://share.getcloudapp.com/4gujZnBP

**Comment by joshmorel** [comment]
According to this - https://stackoverflow.com/questions/18777130/mongodb-sorting-by-geonear-and-date - we can't use `$geoNear` with `$sort` to sort by distance then createdAt. Any thoughts @Naraujo13 ?

https://github.com/FightPandemics/FightPandemics/blob/43f8f80d2c887ccb4e5c108f72cd53415372e111/backend/lib/endpoints/posts.js#L127

@rabbi08  I'd say this is "Low Priority" (but still should be resolved) but if you disagree feel free to remove the tag. One thing we should definitely sort by `createdAt` only for activity on Profile.

**Comment by Naraujo13** [comment]
The new post is shown not as first or just isn't shown at all?
Just to be sure, the first case is sorting, second one probably just not making the request to update the feed after completing the posts creation.


@joshmorel this link is about sorting on find. We are using geonear on aggregate, it generates a distance field. If sorting by creation date as a second criteria is really important we can add a sort step on the agg pipeline that sorts by distance field and creation date, just like the second answer on that link.

TBH that would be a second sorting (first is by geo and generates distances, second sorts by creation), so would make the query a bit slower. The creation date would be a secondary sorting criteria, so it would only make a difference if both posts are withe exactly the same coordinates, what would happen only with users that manually entered their addresses (because with sharing location we get the exact coordinates, and it is very unlikely to tie up).

**Comment by joshmorel** [comment]
@Naraujo13 it would really only affect the user's own posts within the global feed so personally I'm not sure how important that is. Within profile activity - if we omit location part of search maybe that would suffice? (so it skips location just like if it's unauthenticated)

**Comment by Naraujo13** [comment]
Yeah, I think so.

That could work.
Other option would be to add a parameter to the endpoint that sets the sorting and defaults to location?

**Comment by joshmorel** [comment]
I think a parameter would work. Either way I dont think this is critical for soft launch so we should focus on other issues for now.

**Comment by joshmorel** [comment]
@rabbi08  I created a separate issue - #904 for profile page. This one requires further discussion to decide on how we want to order the main feed and is v1.1 or later I think.

**Comment by joshmorel** [comment]
@rabbi08 so with this fix  #1320 the most recent post will display first for the exact same coordinates (regardless of author -  own or others). 

I think we should close this as this will be the expected sorting order for v1.0.

We've discussed doing more complicated things with the personal help board feed but that will be v1.1.

**Comment by rabbi08** [comment]
> @rabbi08 so with this fix #1320 the most recent post will display first for the exact same coordinates (regardless of author - own or others).
> 
> I think we should close this as this will be the expected sorting order for v1.0.
> 
> We've discussed doing more complicated things with the personal help board feed but that will be v1.1.

@joshmorel Agree, As per the testing done for #1322, recent post as per location match, is displayed first. Hence we can close this. 
thanks
