### ISSUE TITLE
Post Creation page design doesn't math Zeplin

### ISSUE THREAD

**Issue by omarzoghayyer** [FightPandemics/FightPandemics#962]
After posting an organization/individual post, the after post message doesn't match the one on Zeplin.

ACTUAL
<img width="521" alt="Screen Shot 2020-07-01 at 8 34 35 PM" src="https://user-images.githubusercontent.com/49251966/86313661-89f4ae00-bbda-11ea-9305-63c2eab31f57.png">

ZEPLIN
<img width="786" alt="Screen Shot 2020-07-01 at 8 34 30 PM" src="https://user-images.githubusercontent.com/49251966/86313674-90832580-bbda-11ea-8b88-984d8f1fdd70.png">

**Comment by ppagarawal** [comment]
@omarzoghayyer There were a few changes made on the designs. I would like to know what changes you are referring to here. Please reach out to me before making changes.

**Comment by ppagarawal** [comment]
@omarzoghayyer The changes we have in staging is fine and does not need any change. Please close this ticket without any changes.

**Comment by idjevm** [comment]
This is a duplicate. And a loooong discussion has been going on. Closing this one as this changes are not needed. Please keep do not make any changes @omarzoghayyer

**Comment by omarzoghayyer** [comment]
@ppagarawal no changes were made. Lets try to follow Zeplin as the current design doesn't look good.

**Comment by idjevm** [comment]
@omarzoghayyer yeah for this one we decided to change it since there isn't a way to check yet if the user has completed the profile or not and what does that look like? Do they miss something or a new profile? Yeah there were a lot of things that we considered. Also, the design looks a bit funky because there was a PR that was merged that messed up some of the buttons design. It is already being resolved with PR #937. Thank you for pointing this out though, we should have the design team refactor and redo some parts of the design. Although this will probably make sense later
