### ISSUE TITLE
Create an organization profile for Sourced by FP org account

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#967]
Some open questions here- @manualzuru 

1. Which individual user account should this be linked to? Do we have some type of an admin user profile? 

2. Does it make sense to include this in the soft launch (e.g., are mutual aid groups going to be commenting/trying to connect with the requests that are sourced by FP)? If so, on our end, we also need to have this be linked to our support accounts or something and have a way to be able to respond to them. If not for soft launch but for MVP, we probably still need to figure that out. 

3. I think we should also make the location for this worldwide. Thoughts?

**Comment by manualzuru** [comment]
We just need to have an organization account linked to all of those post. Maybe admin@fightpandemics.com. @joshmorel how can we link them?

**Comment by joshmorel** [comment]
@manualzuru @vikjoshi 

We have organization account linked but there's no about, contact info or anything because I only populated required elements.

See:
https://staging.fightpandemics.work/organization/5edc1d3efe8dbf11199b26ad

The individual owner account has email sourcedby@fightpandemics.com

I can create an account password etc so someone can go in and & manage their profiles - there are 9 - one for each organization type (required because of the way we have author provider type as a filter).

Each of organization email is like:
sourcedby-type-non-profit@fightpandemics.com
sourcedby-type-other@fightpandemics.com
Etc

Let me know what you would like me to do.

**Comment by joshmorel** [comment]
I'll update to admin@fightpandemics.com . The problem is email needs to be unique so the orgs need to use something else.

If the owner is notified this shouldn't be a problem. Unless we want to update logic so email only needs to be unique for IndividualUser or maybe email/type is a unique combination?
