### ISSUE TITLE
Not able to identify my location using GPS on Android mobile devices.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#985]
Steps to create:
 Device used (Samsung Galaxy)
-Login with valid emailid,password.
-click on request help.
-click on medical.
-click on share my location
![Screenshot_20200703-153806_Samsung Internet](https://user-images.githubusercontent.com/41587211/86496181-28535180-bd4a-11ea-9174-020c1378b10f.jpg)

**Comment by joshmorel** [comment]
@nivetheatha  The message indicates the browser geolocation didn't work. There could be a few different reasons for this.

Did you give permission to "use your device's location"?

If so maybe it couldn't get geolocation from the device for some reason.

What browser are you using and do other sites work with geolocation? Samsung Android worked fine for me.

Anyways, it's expected that this might not work sometimes so that's why I put the specific message prompts the user to input the address.

**Comment by nivetheatha** [comment]
It's not working in Samsung internet browser. 
But working well in chrome and firefox.

**Comment by joshmorel** [comment]
:man_shrugging: Hmmm it is working for me in Samsung Browser.

Anyways, I think we should close this issue. The [browser's Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) can not always be relied on to work depending on various issues with browser, device, user not providing permission, other random issues. That's why we suggest they manually enter the address in such a case.

**Comment by nivetheatha** [comment]
Ok will close this issue.
