### ISSUE TITLE
Feed - [Mobile - IOS] - When "Make Surgical Masks: Materials and..." is clicked the content does not fit to page

### ISSUE THREAD

**Issue by dabartlett** [FightPandemics/FightPandemics#987]
When "Make Surgical Masks: Materials and..." is clicked the content does not fit to page

Steps to Reproduce:
**Pre-requisite:** Have a user created to sign in

1 - Using mobile (IOS - I used Iphone 6S and simulator 7, 8, X) - staging.fightpandemics.work
2 - Click on 3 line Sign in/Register -> follow sign in steps
3 - Click on Request help -> Medical> Enter any zip/address -> Skip
4 - On Feed: Scroll down to "Make Surgical Masks: Materials..." -> click on it or View More
 
Current Results: Content does not fit to page
Expected Results: Content need to fit to page

![image](https://user-images.githubusercontent.com/67716598/86500711-de696c00-bd47-11ea-9c80-a2807ae38155.png)

**Comment by idjevm** [comment]
@dabartlett can you include the link of the post? -> Posts are shown as nearest to my location, and there are a couple thousand so I won't be able to scroll to find this since I am not sure where the location is. Better if you include the post link here. I want to test cuz I think this is being resolved...

**Comment by idjevm** [comment]
I actually fond it since I figured you were looking at posts near Nevada or the US in general, and yeah I tested and this is the same issue as #928, and it is being addressed there. I will close this but feel free to test it on the Build URL of this PR -> https://github.com/FightPandemics/FightPandemics/pull/989

**Comment by dabartlett** [comment]
ok - apologies - I see that it is fixed and here is the link just in case: https://staging.fightpandemics.work/post/5eea73164b96a349da599533
